# Generated by Django 6.0.1 on 2026-02-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0002_shorturl_click_count_shorturl_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
